[account_api]
url = "https://silver-pay.com/auth/clientjson"
type = "BINOPT"

[rates_api]
url = "http://currency.silver-pay.com:3030/rates"
get_interval = 5000

[update_server]
url = "http://localhost:8080"
check_interval = 5000
